# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

title: "Nate Saffold"
description: "Developing instrumentation to explore the cosmos"
url: "https://natesaffold.github.io"
baseurl: ""  # "" for user site, or "/repo" for a project site

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed

timezone: America/Chicago
markdown: kramdown
highlighter: rouge

collections:
  research:
    output: false
    permalink: /research/:path/

  teaching:
    output: true
    permalink: /teaching/:path/

include:
  - assets
